# Generated by Django 4.2.7 on 2023-11-02 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=250, verbose_name='Место')),
                ('time', models.TimeField(verbose_name='Время, когда')),
                ('move', models.TextField(verbose_name='Действие')),
                ('sign_good_habit', models.BooleanField(default=True, verbose_name='Признак приятной привычки')),
                ('interval', models.CharField(choices=[('day', 'каждый день'), ('week', 'раз в неделю'), ('month', 'раз в месяц')], default='day', max_length=5, verbose_name='Периодичность')),
                ('reward', models.CharField(blank=True, max_length=100, null=True, verbose_name='Вознаграждение')),
                ('time_to_complete', models.TimeField(verbose_name='Время на выполнение')),
                ('is_public', models.BooleanField(default=True, verbose_name='Признак публичности')),
                ('habit_binding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit', verbose_name='Связанная привычка')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Приятная привычка',
                'verbose_name_plural': 'Приятные привычки',
            },
        ),
    ]
